# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{file_column}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sebastian Kanthak"]
  s.date = %q{2011-09-26}
  s.description = %q{file upload and rmagick image resizing}
  s.email = %q{sebastian.kanthak@muehlheim.de}
  s.extra_rdoc_files = [
    "README",
    "TODO"
  ]
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "init.rb",
    "lib/file_column.rb",
    "lib/file_column_helper.rb",
    "lib/file_compat.rb",
    "lib/magick_file_column.rb",
    "lib/rails_file_column.rb",
    "lib/test_case.rb",
    "lib/validations.rb",
    "test/abstract_unit.rb",
    "test/connection.rb",
    "test/file_column_helper_test.rb",
    "test/file_column_test.rb",
    "test/fixtures/entry.rb",
    "test/fixtures/invalid-image.jpg",
    "test/fixtures/kerb.jpg",
    "test/fixtures/mysql.sql",
    "test/fixtures/schema.rb",
    "test/fixtures/skanthak.png",
    "test/magick_test.rb",
    "test/magick_view_only_test.rb"
  ]
  s.homepage = %q{http://github.com/tekin/file_column}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{file upload and rmagick image resizing}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

